// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proyecto_TBD.Models;

#nullable disable

namespace proyecto_TBD.Migrations
{
    [DbContext(typeof(MydbContext))]
    partial class MydbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb3_general_ci")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb3");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("proyecto_TBD.Models.Donativo", b =>
                {
                    b.Property<int>("Iddonativos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iddonativos");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Iddonativos"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha");

                    b.Property<int?>("IdInstituto")
                        .HasColumnType("int")
                        .HasColumnName("id_instituto");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("Iddonativos")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdInstituto" }, "idinstituciones_idx");

                    b.HasIndex(new[] { "IdProducto" }, "idproductos_idx");

                    b.HasIndex(new[] { "IdUsuario" }, "idusuario_idx");

                    b.ToTable("donativos", (string)null);
                });

            modelBuilder.Entity("proyecto_TBD.Models.Institucione", b =>
                {
                    b.Property<int>("IdInstituto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_instituto");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdInstituto"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Direccion")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("direccion");

                    b.Property<int>("ID_usuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("telefono");

                    b.HasKey("IdInstituto")
                        .HasName("PRIMARY");

                    b.ToTable("instituciones", (string)null);
                });

            modelBuilder.Entity("proyecto_TBD.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Descripción")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripción");

                    b.Property<int>("ID_usuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PesoAprox")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("peso_Aprox");

                    b.HasKey("IdProducto")
                        .HasName("PRIMARY");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("proyecto_TBD.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("correo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreEmpresa")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre_empresa");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("telefono");

                    b.HasKey("IdUsuario")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Correo" }, "correo_UNIQUE")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("proyecto_TBD.Models.Donativo", b =>
                {
                    b.HasOne("proyecto_TBD.Models.Institucione", "IdInstitutoNavigation")
                        .WithMany("Donativos")
                        .HasForeignKey("IdInstituto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("idinstituciones");

                    b.HasOne("proyecto_TBD.Models.Producto", "IdProductoNavigation")
                        .WithMany("Donativos")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("idproductos");

                    b.HasOne("proyecto_TBD.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Donativos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("idusuario");

                    b.Navigation("IdInstitutoNavigation");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("proyecto_TBD.Models.Institucione", b =>
                {
                    b.Navigation("Donativos");
                });

            modelBuilder.Entity("proyecto_TBD.Models.Producto", b =>
                {
                    b.Navigation("Donativos");
                });

            modelBuilder.Entity("proyecto_TBD.Models.Usuario", b =>
                {
                    b.Navigation("Donativos");
                });
#pragma warning restore 612, 618
        }
    }
}
